delete a comment by comment_id
davegreensmith/be-nc-games-project pull request #11
Opened 2022-07-07 13:53 UTC by davegreensmith

2022-07-07 14:24 UTC, CatHoang reviewed
Hi Dave, just a small suggestion in your model :)

2022-07-07 14:24 UTC, CatHoang commented on models/models.comments.js
> +    return db.query('DELETE FROM comments WHERE comment_id = $1', [comment_id]);
I would suggest doing your delete first and then checking if that comment exist after to make sure it has been deleted

2022-07-08 09:30 UTC, emilyb93 commented on models/models.comments.js
> +    return Promise.all([db.query('SELECT * FROM comments WHERE comment_id=$1', [comment_id]), rows]).then(([{ rows }, deleteResult]) => {
We dont actually need this line. RETURNING * in an SQL query will return all the rows that have been affected/deleted. If the rows have a length of 0, then we can assume that the comment didnt exist in the first place, where as if we get a length of 1, then it did exist and has now been deleted.

2022-07-08 09:30 UTC, emilyb93 requested changes
^

2022-07-08 09:59 UTC, two-triangles commented
looks good :) Happy to merge :)

2022-07-08 10:13 UTC, merged